spring:
  application:
    name: aws-sqs-sleuth-consumer-poc

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    region:
      auto: false
      static: ${AWS_REGION}
    stack:
      auto: false

app:
  queue:
    name: ${QUEUE_NAME}